name: build
on:
  push:
  
jobs:        
  brew:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0]
    steps:
    - uses: Homebrew/actions/setup-homebrew@master
    - run: brew test-bot --skip-recursive-dependents